language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: Oc8MWvB7qewxjhWc2Tdki5oM2oEDVFDOtZbWWobNzgtquAeRK7azFCwlmRZImTRdLVvFN0Sm08VMXQWLVlqpn6hHmMLgp3+2bqJ8Ti3KoBPG/mg6AUqqERd3/PyfDoTR7xsB1rN/eNFuyl8pLJPEpccRxJE3DhF2Mt5LhhacnM32TCHL3/r1Bl5gsEiwK8oSGPz0xFB+pyfQFAujdXEMR3WNy9j+T0f05dw+MCwpPhk8n92hI5UqFtMA2+jbxHlYUCtPLsDc29zZ3SBvxuH5MIAFIigR8xWt7BANn7XBM0E3OB0QRHyI0LCDrNmQAfLeQvoQy6BB+J/GGRx21p3+imNW/SKbwaOxR1p8ut6QOmvS89JM6UFRrYEInxxig1kqyLzHqexGxODbWmZpvEJTOjC2nMmbhQi5lTu4nOxmJ2hVoWWsS1tNfzVKZb4Y6ksB7jVfzjigHNo5Pek6afJafHqP9zOO3GNxTIThGJ8kNoBPEx47VdZieWudzjesQEqTvi8uzLBhxr8Xe1fvsKKIrd0vgQPWfR/lPBefDGNVCYMvQVwhDWkdxpWjOtj8dIaMszYV5E8uArVw7tKW+vDN+YzHseomFSr1PLQyt5dfoUC6qWzaN1cMNQQRlViXJKD9Zd9tNtMlrhL+g4uY7Eh9QLlfG6fW2DQfgdVgQbhw5fM=
  app: pacific-beyond-48372
  on:
    repo: sulfurshade/node-shopping-list-integration-tests
